@url=http://localhost:4000
@api={{url}}/api
@trpc={{url}}/trpc

GET {{api}}/questions

###

GET {{api}}/question/10

###

POST {{api}}/question/start/create
Content-Type: application/json

###

POST {{api}}/question/start/submit
Content-Type: application/json

###

POST {{api}}/question/predict/create
Content-Type: application/json

###

POST {{api}}/question/predict/submit
Content-Type: application/json

###

POST {{api}}/question/claim/create
Content-Type: application/json

###

POST {{api}}/question/claim/submit
Content-Type: application/json