POST http://localhost:4000/trpc/userCreate

{
  "name": "adsca",
  "id": "11"
}

###

GET http://localhost:4000/trpc/userList

###

GET http://localhost:4000/trpc/userById?input="11"

###

POST http://localhost:4000/api/users
Content-Type: application/json

{
  "name": "adsca",
  "id": "11"
}

###

GET http://localhost:4000/api/users

###

GET http://localhost:4000/api/users/9
